In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão de Python Neste Jupyter Notebook:', python_version())

# usaremos o filtro 'waning' para deixar mais limpo.
import warnings
warnings.filterwarnings('ignore')

Versão de Python Neste Jupyter Notebook: 3.10.5


In [2]:
# Import Numpy Library
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from IPython.display import Image

### Numpy Array Creation

In [3]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [4]:
# Display the type of an object
type(list1)

list

In [5]:
#Convert list to Numpy Array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [6]:
#Memory address of an array object
arr1.data

In [7]:
# Display type of an object
type(arr1)

numpy.ndarray

In [8]:
#Datatype of array
arr1.dtype

dtype('int32')

In [9]:
# Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
#Shape of Array
arr3 = np.arange(0,10)
arr3.shape

(10,)

In [14]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Size of array
arr3.size

10

In [16]:
# Dimension
arr3.ndim

1

In [17]:
# Datatype of object
arr3.dtype

dtype('int32')

In [18]:
# Bytes consumed by one element of an array object
arr3.itemsize

4

In [19]:
# Bytes consumed by an array object
arr3.nbytes

40

In [20]:
# Length of array
len(arr3)

10

In [21]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [24]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [25]:
# Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [26]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 ==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Generate evenly spaced 4 numbers between 10 to 20.
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [29]:
# Generate evenly spaced 11 numbers between 10 to 20.
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [30]:
# Create an array of random values
np.random.random(4)

array([0.05175125, 0.45585028, 0.35846447, 0.38142619])

In [31]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,5)

array([252,  86,  83, 180, 445])

In [32]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,10)

array([356, 109, 173, 206, 436,   6, 322, 154, 477, 271])

In [33]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [34]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [35]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [38]:
# Extract Integer part
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [39]:
# Truncate decimal part
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [40]:
# Convert Float Array to Integer array
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [41]:
# Normal distribution (mean=0 and variance=1)
b2 =np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [42]:
arr1

array([10, 20, 30, 40, 50, 60])

In [43]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


### Operations on an Array

In [44]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
# Sum of all elements in an array
arr2.sum()

190

In [46]:
# Cumulative Sum
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

In [47]:
# Find Minimum number in an array
arr2.min()

1

In [48]:
# Find MAX number in an array
arr2.max()

19

In [49]:
# Find INDEX of Minimum number in an array
arr2.argmin()

0

In [50]:
# Find INDEX of MAX number in an array
arr2.argmax()

18

In [51]:
# Find mean of all numbers in an array
arr2.mean()

10.0

In [52]:
# Find median of all numbers present in arr2
np.median(arr2)

10.0

In [53]:
# Variance
np.var(arr2)

30.0

In [54]:
# Standard deviation
np.std(arr2)

5.477225575051661

In [55]:
# Calculating percentiles
np.percentile(arr2,70)

13.6

In [56]:
# 10th & 70th percentile
np.percentile(arr2,[10,70])

array([ 2.8, 13.6])

### Operations on a 2D Array

In [57]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [58]:
# SUM of all numbers in a 2D array
A.sum()

129

In [59]:
# MAX number in a 2D array
A.max()

22

In [60]:
# Minimum
A.min()

0

In [61]:
# Column wise mimimum value
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [62]:
# Row wise mimimum value
np.amin(A, axis=1)

array([0, 5, 1, 3])

In [63]:
# Mean of all numbers in a 2D array
A.mean()

8.0625

In [64]:
# Mean
np.mean(A)

8.0625

In [65]:
# Median
np.median(A)

6.5

In [66]:
# 50 percentile = Median
np.percentile(A,50)

6.5

In [67]:
np.var(A)

40.30859375

In [68]:
np.std(A)

6.348904925260734

In [69]:
np.percentile(arr2,70)

13.6

In [70]:
...

Ellipsis

In [71]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0



### End.